export type PairState =
  | 'DRAFT'
  | 'AUTHORING'
  | 'VALIDATING'
  | 'REPAIR_REQUIRED'
  | 'VALIDATED';

export type DomainState =
  | 'IN_PROGRESS'
  | 'DOMAIN_VALIDATING'
  | 'REPAIR_REQUIRED'
  | 'READY_FOR_APPROVAL'
  | 'APPROVED'
  | 'PUBLISHED';

export type RepairState = 'OPEN' | 'REPAIRING' | 'REVALIDATING' | 'RESOLVED';

export type CognitiveTaskType =
  | 'PAIR_BOUNDARY'
  | 'AP_FAILURE_MODEL'
  | 'APPLICABILITY'
  | 'PRIMARY_QUESTIONS'
  | 'ATOMIC_DECOMPOSITION'
  | 'EVIDENCE_ARCHITECTURE'
  | 'EVIDENCE_SAFETY'
  | 'SOURCE_MAPPING'
  | 'FINDING_ARCHITECTURE'
  | 'CONTROL_BOUNDARY'
  | 'REFERENCE_MAPPING'
  | 'PAIR_COHERENCE_REVIEW'
  | 'DOMAIN_COHERENCE_REVIEW'
  | 'LOCAL_REPAIR';
